// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/template-speakeasy-bar/pkg/models/shared"
	"net/http"
)

type AuthenticateRequestBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

func (o *AuthenticateRequestBody) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *AuthenticateRequestBody) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

// Authenticate200ApplicationJSON - The api key to use for authenticated endpoints.
type Authenticate200ApplicationJSON struct {
	Token *string `json:"token,omitempty"`
}

func (o *Authenticate200ApplicationJSON) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

type AuthenticateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// An unknown error occurred interacting with the API.
	Error *shared.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The api key to use for authenticated endpoints.
	Authenticate200ApplicationJSONObject *Authenticate200ApplicationJSON
}

func (o *AuthenticateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AuthenticateResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *AuthenticateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AuthenticateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AuthenticateResponse) GetAuthenticate200ApplicationJSONObject() *Authenticate200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.Authenticate200ApplicationJSONObject
}
