// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/template-speakeasy-bar/pkg/models/shared"
	"net/http"
)

type ListDrinksRequest struct {
	// The type of drink to filter by. If not provided all drinks will be returned.
	DrinkType *shared.DrinkType `queryParam:"style=form,explode=true,name=drinkType"`
}

func (o *ListDrinksRequest) GetDrinkType() *shared.DrinkType {
	if o == nil {
		return nil
	}
	return o.DrinkType
}

type ListDrinksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of drinks.
	Drinks []shared.Drink
	// An unknown error occurred interacting with the API.
	Error *shared.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListDrinksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDrinksResponse) GetDrinks() []shared.Drink {
	if o == nil {
		return nil
	}
	return o.Drinks
}

func (o *ListDrinksResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ListDrinksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDrinksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
