// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *Error) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Error) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
