// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// IngredientType - The type of ingredient.
type IngredientType string

const (
	IngredientTypeFresh    IngredientType = "fresh"
	IngredientTypeLongLife IngredientType = "long-life"
	IngredientTypePackaged IngredientType = "packaged"
)

func (e IngredientType) ToPointer() *IngredientType {
	return &e
}

func (e *IngredientType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fresh":
		fallthrough
	case "long-life":
		fallthrough
	case "packaged":
		*e = IngredientType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IngredientType: %v", v)
	}
}
