// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OrderInput - An order for a drink or ingredient.
type OrderInput struct {
	// The product code of the drink or ingredient.
	ProductCode string `json:"productCode"`
	// The number of units of the drink or ingredient to order.
	Quantity int64 `json:"quantity"`
	// The type of order.
	Type OrderType `json:"type"`
}

func (o *OrderInput) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

func (o *OrderInput) GetQuantity() int64 {
	if o == nil {
		return 0
	}
	return o.Quantity
}

func (o *OrderInput) GetType() OrderType {
	if o == nil {
		return OrderType("")
	}
	return o.Type
}

// OrderStatus - The status of the order.
type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusComplete   OrderStatus = "complete"
)

func (e OrderStatus) ToPointer() *OrderStatus {
	return &e
}

func (e *OrderStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "processing":
		fallthrough
	case "complete":
		*e = OrderStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderStatus: %v", v)
	}
}

// Order - An order for a drink or ingredient.
type Order struct {
	// The product code of the drink or ingredient.
	ProductCode string `json:"productCode"`
	// The number of units of the drink or ingredient to order.
	Quantity int64 `json:"quantity"`
	// The status of the order.
	Status OrderStatus `json:"status"`
	// The type of order.
	Type OrderType `json:"type"`
}

func (o *Order) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

func (o *Order) GetQuantity() int64 {
	if o == nil {
		return 0
	}
	return o.Quantity
}

func (o *Order) GetStatus() OrderStatus {
	if o == nil {
		return OrderStatus("")
	}
	return o.Status
}

func (o *Order) GetType() OrderType {
	if o == nil {
		return OrderType("")
	}
	return o.Type
}
